kind: Deployment
apiVersion: apps/v1
metadata:
  name: covid19info-backend
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      name: covid19info
      labels:
        app: covid19info
        role: backend
        env: production
    spec:
      containers:
        - name: covid19info
          image: localhost:5000/covid19info
          #          resources:
          #            limits:
          #              memory: "500Mi"
          #              cpu: "100m"
          imagePullPolicy: Always
          readinessProbe:
            # Readiness probe is used to check if this app is ready to serve traffic.
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 10
          livenessProbe:
            # Liveness probe is used to check if this app is responding to requests
            # (after it is marked as "ready").
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: COMPONENT
              value: backend
            - name: VERSION
              value: production
            - name: jasypt.encryptor.password
              valueFrom:
                configMapKeyRef:
                  name: covid19info-backend-configmap
                  key: JASYPT_ENCRYPTOR_PASSWORD
          ports:
            - name: backend
              containerPort: 8080
      terminationGracePeriodSeconds: 5
  selector:
    matchLabels:
      app: covid19info