kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: covid19info
  labels:
    app: covid19info
    service: covid19info
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
  selector:
    app: covid19info
