kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: covid19info
  labels:
    app: covid19info
    service: covid19info
spec:
  ports:
    - name: 8081-8080
      port: 8081
  selector:
    app: covid19info
  sessionAffinity: None
  type: ClusterIP
